# -*- coding: utf-8 -*-
"""Untitled86.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CaEaaZ_qwEWnuDd_58kO6rwSbsOhHl_W
"""

from google.colab import drive
drive.mount('/content/drive')

!ls /content/drive/MyDrive

!cp "/content/drive/MyDrive/archive.zip" /content/

!unzip /content/archive.zip -d /content/dataset

import os, shutil

root = "/content/dataset"

brain_root = os.path.join(root, "Brain", "Brain")
heart_root = os.path.join(root, "Heart", "Heart")
lung_root  = os.path.join(root, "archive (1)", "COVID-19_Radiography_Dataset")

final_data = "/content/final_dataset"
shutil.rmtree(final_data, ignore_errors=True)
os.makedirs(final_data, exist_ok=True)

def copy_images(src, dst):
    os.makedirs(dst, exist_ok=True)
    for root, _, files in os.walk(src):
        for f in files:
            if f.lower().endswith((".png",".jpg",".jpeg")):
                shutil.copy(os.path.join(root, f), dst)

# -------- BRAIN --------
brain_map = {
    "glioma": "Brain_Glioma",
    "meningioma": "Brain_Meningioma",
    "pituitary": "Brain_Pituitary",
    "notumor": "Brain_Normal"
}

for split in ["Training","Testing"]:
    for cls in brain_map:
        src = os.path.join(brain_root, split, cls)
        dst = os.path.join(final_data, brain_map[cls])
        copy_images(src, dst)

# -------- HEART --------
copy_images(os.path.join(heart_root,"Normal"),
            os.path.join(final_data,"Heart_Normal"))

copy_images(os.path.join(heart_root,"Sick"),
            os.path.join(final_data,"Heart_Sick"))

# -------- LUNG --------
lung_map = {
    "COVID": "Lung_COVID",
    "Normal": "Lung_Normal",
    "Lung_Opacity": "Lung_LungOpacity",
    "Viral Pneumonia": "Lung_ViralPneumonia"
}

for cls in lung_map:
    src = os.path.join(lung_root, cls, "images")
    dst = os.path.join(final_data, lung_map[cls])
    copy_images(src, dst)

print("Final Classes:", os.listdir(final_data))

for cls in sorted(os.listdir(final_data)):
    print(cls, "→", len(os.listdir(os.path.join(final_data, cls))))

import numpy as np
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from sklearn.utils.class_weight import compute_class_weight

img_size = 224
batch = 32   # GPU-friendly batch size

gen = ImageDataGenerator(
    rescale=1./255,
    validation_split=0.2
)

train = gen.flow_from_directory(
    "/content/final_dataset",
    target_size=(img_size, img_size),
    batch_size=batch,
    subset="training",
    shuffle=True
)

val = gen.flow_from_directory(
    "/content/final_dataset",
    target_size=(img_size, img_size),
    batch_size=batch,
    subset="validation",
    shuffle=False
)

# ---- CLASS WEIGHTS (VERY IMPORTANT) ----
class_weights = compute_class_weight(
    class_weight="balanced",
    classes=np.unique(train.classes),
    y=train.classes
)

class_weights = dict(enumerate(class_weights))
print("Class Weights:", class_weights)

class_indices = train.class_indices
labels = list(class_indices.keys())
print("Class Indices:", class_indices)
print("Labels:", labels)

import tensorflow as tf

inputs = tf.keras.Input(shape=(224,224,3))

x = tf.keras.layers.Conv2D(32,3,activation="relu")(inputs)
x = tf.keras.layers.MaxPooling2D()(x)

x = tf.keras.layers.Conv2D(64,3,activation="relu")(x)
x = tf.keras.layers.MaxPooling2D()(x)

x = tf.keras.layers.Conv2D(128,3,activation="relu")(x)
x = tf.keras.layers.GlobalAveragePooling2D()(x)

x = tf.keras.layers.Dense(128, activation="relu")(x)
x = tf.keras.layers.Dropout(0.4)(x)

outputs = tf.keras.layers.Dense(10, activation="softmax")(x)

model = tf.keras.Model(inputs, outputs)

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-4),
    loss="categorical_crossentropy",
    metrics=["accuracy"]
)

model.summary()

history = model.fit(
    train,
    validation_data=val,
    epochs=25,
    class_weight=class_weights
)

model.save("/content/drive/MyDrive/final_disease_model.h5")
print("✅ Model permanently saved to Drive")

from tensorflow.keras.models import load_model
model = load_model("/content/drive/MyDrive/final_disease_model.h5")
print("✅ Model loaded from Drive")

!cp "/content/drive/MyDrive/final_disease_model.h5" "/content"

